# -*- coding: utf-8 -*-
"""safari_news.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v5ynEisSyjB_0ZEgAg3oZUBlye5TnkO8
"""


import smtplib
import tempfile
import shutil
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException, NoSuchElementException, WebDriverException
import logging
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.support.ui import WebDriverWait
from webdriver_manager.chrome import ChromeDriverManager

import pandas as pd
import time
import re
import psycopg2
import logging
from datetime import datetime

class WebScraper():

  def scraper_driver(self, url):
    #self.user_data_dir = None
    self.logger = logging.getLogger(__name__)
    # Setup headless Chrome
    options = Options()
    options.add_argument('--headless')
    options.add_argument('--no-sandbox') # Essential for running Chrome in a containerized environment like Colab
    options.add_argument('--disable-dev-shm-usage') # Overcomes limited resource problems
    options.binary_location = "/usr/bin/google-chrome"

    service = Service(ChromeDriverManager().install())

    self.driver = webdriver.Chrome(service=service, options=options)

    #Initialize the Webdriver
    self.wait = WebDriverWait(self.driver, 2)
    self.driver.get(url)

  def scrape(self):
    news_list = []
    self.driver.implicitly_wait(0.5)
    all_news = self.driver.find_elements(by=By.CSS_SELECTOR, value="article.item")
    for news in all_news:
      news = news.text
      news_list.append(news)

    news_clean = [i.replace("\n", " ") for i in news_list]
    html_content = str(news_clean)
    self.driver.quit()
    return html_content

# Email
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

class EmailSender():

  def send_email(self, subject, sender, recipients, password, html_content):
    # Create email message container
    msg = MIMEMultipart("alternative")
    msg['Subject'] = subject
    msg['From'] = sender
    msg['To'] = ', '.join(recipients)

    # Attach HTML content
    html_part = MIMEText(html_content, "plain", "utf-8")
    msg.attach(html_part)

    # Send the email
    with smtplib.SMTP_SSL('smtp.gmail.com', 465) as smtp_server:
        smtp_server.login(sender, password)
        smtp_server.sendmail(sender, recipients, msg.as_string())
    print("Message sent!")

def main():
  # Email configuration
  subject = "Novinky ze Safari"
  sender = "v.tetour@gmail.com"
  recipients = ["vlkscraper@outlook.com", "v.tetour@gmail.com"]
  password = "hyhe qdhx ntsu cvqs"

  webscraper = WebScraper()
  webscraper.scraper_driver("https://safaripark.cz/")
  html_content = webscraper.scrape()

  email_sender = EmailSender()
  email_sender.send_email(subject, sender, recipients, password, html_content=html_content)

if __name__ == "__main__":
  main()
